### ISSUE TITLE
Failing to build cross platform app in the CI/CD Pipeline

### ISSUE THREAD

**Issue by NupurThakur27** [fyne-io/fyne-cross#58] opened 2021-08-03 15:21 UTC
Command used in the pipeline where both the dependencies `go` and `docker` are present.
`fyne-cross windows -output file-transfer-service ./src/cmd/gui/`

Error :
```
could not create the rc file: open /app/fyne-cross/tmp/windows-amd64/main.rc: permission denied
[✗] could not package the Fyne app: exit status 1
```

**Comment by Jacalz** [comment] 2021-08-03 17:05
I think this is a consequence of how docker handles permissions. If the user isn’t part of the `docker` group you will have to run using sudo which can result in potential issues. See https://docs.docker.com/engine/install/linux-postinstall/ for more information.

I think https://github.com/fyne-io/fyne-cross/pull/42 should make this much easier once that has landed.

**Comment by andydotxyz** [comment] 2021-08-03 18:58
Perhaps duplicate of #20 ?

**Comment by Jacalz** [comment] 2021-08-03 19:00
I agree. It is a duplicate of that issue.

**Closed** 2021-08-03 19:00 UTC
Labels: duplicate
