### ISSUE TITLE
Can't build for Windows from Darwin with Go 1.16

### ISSUE THREAD

**Issue by unquabain** [fyne-io/fyne-cross#59] opened 2021-08-06 20:20 UTC
My project builds and runs on Darwin using Go 1.16. But when I use fyne-cross to build a Windows binary, several dependency libraries fail to compile because—it appears—the Go version in the Docker containers are older.

From the output:

```
api/authenticate.go:77:16: undefined: io.ReadAll
api/diagnostics.go:44:16: undefined: io.ReadAll
note: module requires Go 1.16
# github.com/xuri/excelize/v2
/go/pkg/mod/github.com/xuri/excelize/v2@v2.4.1/calc.go:1907:18: undefined: strconv.ParseComplex
/go/pkg/mod/github.com/xuri/excelize/v2@v2.4.1/calc.go:1923:18: undefined: strconv.ParseComplex
/go/pkg/mod/github.com/xuri/excelize/v2@v2.4.1/calc.go:1939:18: undefined: strconv.ParseComplex
/go/pkg/mod/github.com/xuri/excelize/v2@v2.4.1/calc.go:1955:18: undefined: strconv.ParseComplex
/go/pkg/mod/github.com/xuri/excelize/v2@v2.4.1/calc.go:1971:18: undefined: strconv.ParseComplex
/go/pkg/mod/github.com/xuri/excelize/v2@v2.4.1/calc.go:1987:18: undefined: strconv.ParseComplex
/go/pkg/mod/github.com/xuri/excelize/v2@v2.4.1/calc.go:2003:18: undefined: strconv.ParseComplex
/go/pkg/mod/github.com/xuri/excelize/v2@v2.4.1/calc.go:2019:18: undefined: strconv.ParseComplex
/go/pkg/mod/github.com/xuri/excelize/v2@v2.4.1/calc.go:2039:18: undefined: strconv.ParseComplex
/go/pkg/mod/github.com/xuri/excelize/v2@v2.4.1/calc.go:2059:19: undefined: strconv.ParseComplex
/go/pkg/mod/github.com/xuri/excelize/v2@v2.4.1/calc.go:2059:19: too many errors
note: module requires Go 1.15
[✗] exit status 2
```

I can update the version of Go in a running fyne-cross docker container, but how can I tell the `fyne-cross` command to use my own container or image?

**Comment by Jacalz** [comment] 2021-08-07 08:19
The latest release does have Go 1.16 inside the containers. Are you sure that you have the latest release installed and the latest images pulled?

You can install the latest fyne-cross using `go install github.com/fyne-io/fyne-cross@latest` and pulling the latest images using `fyne-cross windows —pull`.

**Comment by lucor** [comment] 2021-09-30 16:24
@unquabain did you had a chance to test the steps suggested by @Jacalz ?

**Comment by Jacalz** [comment] 2022-03-29 19:42
@unquabain Can you still reproduce this using the steps mentioned above?

**Comment by andydotxyz** [comment] 2023-02-23 11:31
Many updates have been applied since this ticket, closing

**Closed by andydotxyz** 2023-02-23 11:31 UTC
Labels: question
