### ISSUE TITLE
linux cross-compile problem

### ISSUE THREAD

**Issue by 0x414a** [fyne-io/fyne-cross#224] opened 2024-03-12 06:46 UTC
Apple M1
 macOS13.2 (22D49)
 
 Cross compilation is no problem, recently encountered this, several days did not solve, do not understand
 
 fyne-cross linux -arch amd64 .
[i] Target: linux/amd64
[i] Cleaning target directories...
docker: Error response from daemon: error while creating mount source path '/host_mnt/private/tmp/com.apple.launchd.AF7voObilD/Listeners': mkdir /host_mnt/private/tmp/com.apple.launchd.AF7voObilD/Listeners: operation not supported.
[✗] could not clean the "temp" dir /app/fyne-cross/tmp/linux-amd64: exit status 125

 fyne-cross linux -arch arm64 .
[i] Target: linux/arm64
[i] Cleaning target directories...
docker: Error response from daemon: error while creating mount source path '/host_mnt/private/tmp/com.apple.launchd.AF7voObilD/Listeners': mkdir /host_mnt/private/tmp/com.apple.launchd.AF7voObilD/Listeners: operation not supported.
[✗] could not clean the "bin" dir /app/fyne-cross/bin/linux-arm64: exit status 125

**Comment by andydotxyz** [comment] 2024-03-12 11:41
This is another duplicate of #214 - updating Fyne-cross should fix the issue, see linked issue or other related #217 for more info.

**Closed by andydotxyz** 2024-03-12 11:41 UTC

**Comment by 0x414a** [comment] 2024-03-12 13:52
> [这是#214](https://github.com/fyne-io/fyne-cross/issues/214)的另一个重复- 更新 Fyne-cross 应该可以解决该问题，请参阅链接问题或其他相关的#217了解更多信息。

But it doesn't solve the problem

**Comment by andydotxyz** [comment] 2024-03-14 21:06
Are you sure you were testing with develop branch like that linked issue instructed?

**Comment by 0x414a** [comment] 2024-03-24 14:06
> Are you sure you were testing with develop branch like that linked issue instructed?

Thanks, solved
