### ISSUE TITLE
/lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by pkk-code** [fyne-io/fyne-cross#17] opened 2020-12-10 18:25 UTC
I build the application using fyne_cross on Macosx.

When i start the application on CentOS 7. I get this error /lib64/libm.so.6: version `GLIBC_2.27' not found.

May i know, how to overcome this error and launch the fyne application on CentOS 7

**Comment by Jacalz** [comment] 2020-12-10 19:42
Could you please check what version of glibc you have on that CentOS 7 machine?

I think that this probably is caused by CentOS 7 using an older version of GLIBC than what fyne-cross links to in the Docker container. If that’s the case, you probably have to build the fyne application on that CentOS 7 machine or run the binary on a newer distribution.

**Comment by pkk-code** [comment] 2020-12-10 21:36
glibc-2.17-292.el7.x86_64 is whats available on the CentOS 7 machine.

I couldn't build the fyne application on that CentOS 7 due fyne-io/fyne#1088

**Comment by lucor** [comment] 2020-12-26 18:51
As @Jacalz pointed out, updating libc should fix.
Below are the versions from the container:
```
root@f64c0d85cf7b:/app# dpkg -l | grep libc
ii  libc-bin                    2.28-10                     amd64        GNU C Library: Binaries
ii  libc-dev-bin                2.28-10                     amd64        GNU C Library: Development binaries
ii  libc6:amd64                 2.28-10                     amd64        GNU C Library: Shared libraries
ii  libc6-dev:amd64             2.28-10                     amd64        GNU C Library: Development Libraries and Header Files
```

**Comment by Jacalz** [comment] 2021-01-14 09:50
I think this perhaps should be closed as it isn't an issue with fyne-cross. I don't think there really is any good way for us to fix this.

**Closed** 2021-01-16 18:51 UTC
Labels: question
