### ISSUE TITLE
Compile to andriod error

### ISSUE THREAD

**Issue by xfengw** [fyne-io/fyne-cross#53] opened 2021-07-13 06:58 UTC
go 1.16 windows10 64
D:\project\mygosoft\src\urlPreciseBlockingWithLoginV2>fyne-cross android -app-id cn.xfeng
[i] Target: android
[i] Cleaning target directories...
[✓] "temp" dir cleaned: D:\project\mygosoft\src\urlPreciseBlockingWithLoginV2\fyne-cross\tmp\android
[✓] "bin" dir cleaned: D:\project\mygosoft\src\urlPreciseBlockingWithLoginV2\fyne-cross\bin\android
[✓] "dist" dir cleaned: D:\project\mygosoft\src\urlPreciseBlockingWithLoginV2\fyne-cross\dist\android
[i] Checking for go.mod: D:\project\mygosoft\src\urlPreciseBlockingWithLoginV2\go.mod
[✓] go.mod found
[i] Packaging app...
go build -buildmode=c-shared -o /tmp/gomobile-work-422684388/lib/armeabi-v7a/liburlPreciseBlockingWithLoginV2.so urlPreciseBlockingWithLoginV2 failed: exit status 1
go: downloading github.com/fyne-io/mobile v0.1.2
/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/gomobile/clipboard_android.go:17:2: github.com/fyne-io/mobile@v0.1.2: Get "https://proxy.golang.org/github.com/fyne-io/mobile/@v/v0.1.2.zip": dial tcp 172.217.24.17:443: connect: connection refused
/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/gomobile/driver.go:9:2: github.com/fyne-io/mobile@v0.1.2: Get "https://proxy.golang.org/github.com/fyne-io/mobile/@v/v0.1.2.zip": dial tcp 172.217.24.17:443: connect: connection refused
/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/gomobile/driver.go:10:2: github.com/fyne-io/mobile@v0.1.2: Get "https://proxy.golang.org/github.com/fyne-io/mobile/@v/v0.1.2.zip": dial tcp 172.217.24.17:443: connect: connection refused
/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/gomobile/driver.go:11:2: github.com/fyne-io/mobile@v0.1.2: Get "https://proxy.golang.org/github.com/fyne-io/mobile/@v/v0.1.2.zip": dial tcp 172.217.24.17:443: connect: connection refused
/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/gomobile/device.go:5:2: github.com/fyne-io/mobile@v0.1.2: Get "https://proxy.golang.org/github.com/fyne-io/mobile/@v/v0.1.2.zip": dial tcp 172.217.24.17:443: connect: connection refused
/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/driver/gomobile/driver.go:13:2: github.com/fyne-io/mobile@v0.1.2: Get "https://proxy.golang.org/github.com/fyne-io/mobile/@v/v0.1.2.zip": dial tcp 172.217.24.17:443: connect: connection refused
/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/painter/gl/gl_gomobile.go:11:2: github.com/fyne-io/mobile@v0.1.2: Get "https://proxy.golang.org/github.com/fyne-io/mobile/@v/v0.1.2.zip": dial tcp 172.217.24.17:443: connect: connection refused
/go/pkg/mod/fyne.io/fyne/v2@v2.0.0/internal/painter/gl/gl_gomobile.go:12:2: github.com/fyne-io/mobile@v0.1.2: Get "https://proxy.golang.org/github.com/fyne-io/mobile/@v/v0.1.2.zip": dial tcp 172.217.24.17:443: connect: connection refused

[✗] could not package the Fyne app: could not package the Fyne app: exit status 1

**Comment by xfengw** [comment] 2021-07-13 07:06
PS D:\project\mygosoft\src\urlPreciseBlockingWithLoginV2> fyne-cross android -app-id cn.xfeng -env GOPROXY=https://goproxy.io
[i] Target: android
[i] Cleaning target directories...
[✓] "bin" dir cleaned: D:\project\mygosoft\src\urlPreciseBlockingWithLoginV2\fyne-cross\bin\android
[✓] "dist" dir cleaned: D:\project\mygosoft\src\urlPreciseBlockingWithLoginV2\fyne-cross\dist\android
[✓] "temp" dir cleaned: D:\project\mygosoft\src\urlPreciseBlockingWithLoginV2\fyne-cross\tmp\android
[i] Checking for go.mod: D:\project\mygosoft\src\urlPreciseBlockingWithLoginV2\go.mod
[✓] go.mod found
[i] Packaging app...
go build -buildmode=c-shared -o /tmp/gomobile-work-230436260/lib/armeabi-v7a/liburlPreciseBlockingWithLoginV2.so urlPreciseBlockingWithLoginV2 failed: exit status 2
# github.com/fyne-io/mobile/app
ld: error: duplicate symbol: display
>>> defined at android.go:38
>>>            $WORK/b175/_x001.o:(display)
>>> defined at android.go:38 (/go/pkg/mod/github.com/fyne-io/mobile@v0.1.2/app/android.go:38)
>>>            $WORK/b175/_x002.o:(.bss+0x0)

ld: error: duplicate symbol: surface
>>> defined at android.go:39
>>>            $WORK/b175/_x001.o:(surface)
>>> defined at android.go:39 (/go/pkg/mod/github.com/fyne-io/mobile@v0.1.2/app/android.go:39)
>>>            $WORK/b175/_x002.o:(.bss+0x4)

ld: error: duplicate symbol: display
>>> defined at android.go:38
>>>            $WORK/b175/_x001.o:(display)
>>> defined at android.c:146
>>>            $WORK/b175/_x004.o:(.bss+0x18)

ld: error: duplicate symbol: surface
>>> defined at android.go:39
>>>            $WORK/b175/_x001.o:(surface)
>>> defined at android.c:147
>>>            $WORK/b175/_x004.o:(.bss+0x1C)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

[✗] could not package the Fyne app: could not package the Fyne app: exit status 1

**Comment by lucor** [comment] 2021-07-13 07:35
It looks like a network connection issue with the proxy:

```dial tcp 172.217.24.17:443: connect: connection refused```

Setting the GOPROXY env var should fix:

```fyne-cross android -app-id cn.xfeng -env GOPROXY=<your_proxy>```

**Comment by xfengw** [comment] 2021-07-13 23:56
D:\project\mygosoft\src\urlPreciseBlockingWithLoginV2>fyne-cross android -app-id cn.xfeng -env GOPROXY=https://goproxy.io
[i] Target: android
[i] Cleaning target directories...
[✓] "bin" dir cleaned: D:\project\mygosoft\src\urlPreciseBlockingWithLoginV2\fyne-cross\bin\android
[✓] "dist" dir cleaned: D:\project\mygosoft\src\urlPreciseBlockingWithLoginV2\fyne-cross\dist\android
[✓] "temp" dir cleaned: D:\project\mygosoft\src\urlPreciseBlockingWithLoginV2\fyne-cross\tmp\android
[i] Checking for go.mod: D:\project\mygosoft\src\urlPreciseBlockingWithLoginV2\go.mod
[✓] go.mod found
[i] Packaging app...
docker: error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: The
 system cannot find the file specified.
See 'docker run --help'.
[✗] could not package the Fyne app: could not package the Fyne app: exit status 127

**Comment by lucor** [comment] 2021-07-14 05:20
it looks like related to user privileges. Could you please make sure you are running from a terminal with same privileges the docker daemon is running?

**Comment by xfengw** [comment] 2021-07-14 06:47
D:\project\mygosoft\src\fyne-examples-develop>fyne-cross android -app-id cn.xfeng -env GOPROXY=https://goproxy.io
[i] Target: android
[i] Cleaning target directories...
[✓] "bin" dir cleaned: D:\project\mygosoft\src\fyne-examples-develop\fyne-cross\bin\android
[✓] "dist" dir cleaned: D:\project\mygosoft\src\fyne-examples-develop\fyne-cross\dist\android
[✓] "temp" dir cleaned: D:\project\mygosoft\src\fyne-examples-develop\fyne-cross\tmp\android
[i] Checking for go.mod: D:\project\mygosoft\src\fyne-examples-develop\go.mod
[✓] go.mod found
[i] Packaging app...
Unable to find image 'fyneio/fyne-cross:1.1-android' locally
1.1-android: Pulling from fyneio/fyne-cross
d960726af2be: Already exists
e8d62473a22d: Already exists
8962bc0fad55: Already exists
65d943ee54c1: Already exists
f2253e6fbefa: Already exists
186c77a2a533: Pull complete
db807893dccf: Pull complete
292f24f0ff89: Pull complete
974bf8135e20: Pull complete
6f6e9bee4d1e: Pull complete
566c48a9b3d8: Pull complete
9019a4581f1b: Pull complete
282dd26a693f: Pull complete
Digest: sha256:b3d36509c011277176432d6faf5548437922146b7522c93360238c60aa70e1aa
Status: Downloaded newer image for fyneio/fyne-cross:1.1-android
go build -buildmode=c-shared -o /tmp/gomobile-work-971235108/lib/armeabi-v7a/libfyne_examples_develop.so github.com/fyne-io/examples failed: exit status 2
# github.com/fyne-io/mobile/app
ld: error: duplicate symbol: display
>>> defined at android.go:38
>>>            $WORK/b175/_x001.o:(display)
>>> defined at android.go:38 (/go/pkg/mod/github.com/fyne-io/mobile@v0.1.2/app/android.go:38)
>>>            $WORK/b175/_x002.o:(.bss+0x0)

ld: error: duplicate symbol: surface
>>> defined at android.go:39
>>>            $WORK/b175/_x001.o:(surface)
>>> defined at android.go:39 (/go/pkg/mod/github.com/fyne-io/mobile@v0.1.2/app/android.go:39)
>>>            $WORK/b175/_x002.o:(.bss+0x4)

ld: error: duplicate symbol: display
>>> defined at android.go:38
>>>            $WORK/b175/_x001.o:(display)
>>> defined at android.c:146
>>>            $WORK/b175/_x004.o:(.bss+0x18)

ld: error: duplicate symbol: surface
>>> defined at android.go:39
>>>            $WORK/b175/_x001.o:(surface)
>>> defined at android.c:147
>>>            $WORK/b175/_x004.o:(.bss+0x1C)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

[✗] could not package the Fyne app: could not package the Fyne app: exit status 1

**Comment by lucor** [comment] 2021-07-14 06:51
oh it seems we're almost there ... Do you mind to test with a minimal hello world app using the latest version fyne?

**Comment by xfengw** [comment] 2021-07-14 08:23
useing fyne v2.03

**Comment by xfengw** [comment] 2021-07-14 09:07
package main

import (
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/widget"
)

func main() {
	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(container.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}

**Comment by xfengw** [comment] 2021-07-14 09:15
is ok
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All

**Comment by xfengw** [comment] 2021-07-14 09:21
this is ok
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All

**Comment by xfengw** [comment] 2021-07-14 09:29
However, other software that can be compiled and run under windows cannot be compiled to android.


D:\project\mygosoft\src\riskExcel2021>fyne-cross android -app-id cn.xfeng -env GOPROXY=https://goproxy.io
[i] Target: android
[i] Cleaning target directories...
[✓] "bin" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\bin\android
[✓] "dist" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\dist\android
[✓] "temp" dir cleaned: D:\project\mygosoft\src\riskExcel2021\fyne-cross\tmp\android
[i] Checking for go.mod: D:\project\mygosoft\src\riskExcel2021\go.mod
[✓] go.mod found
[i] Packaging app...
go build -buildmode=c-shared -o /tmp/gomobile-work-189930580/lib/armeabi-v7a/libriskExcel2021.so riskExcel2021 failed: exit status 2
# fyne.io/fyne/v2/internal/driver/gomobile
android.c:50:9: warning: returning 'const char *' from a function with result type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
android.c:67:48: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
android.c:71:55: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
android.c:122:48: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
android.c:125:48: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
android.c:181:50: warning: passing 'char *' to parameter of type 'jbyte *' (aka 'signed char *') converts between pointers to integer types with different sign [-Wpointer-sign]
android.c:191:48: warning: passing 'char *' to parameter of type 'const jbyte *' (aka 'const signed char *') converts between pointers to integer types with different sign [-Wpointer-sign]
# fyne.io/fyne/v2/app
app_mobile_and.c:46:48: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
app_mobile_and.c:49:48: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
app_mobile_and.c:72:33: warning: incompatible pointer to integer conversion passing 'JNIEnv *' (aka 'const struct JNINativeInterface **') to parameter of type 'uintptr_t' (aka 'unsigned int') [-Wint-conversion]
app_mobile_and.c:42:36: note: passing argument to parameter 'jni_env' here
# riskExcel2021
/usr/local/go/pkg/tool/linux_amd64/link: running /usr/local/android_sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang failed: exit status 1
ld: error: /tmp/go-link-968878995/000000.o: unknown file type
clang: error: linker command failed with exit code 1 (use -v to see invocation)


[✗] could not package the Fyne app: could not package the Fyne app: exit status 1

**Comment by andydotxyz** [comment] 2021-07-14 09:44
This normally means a stale cache:

> ld: error: /tmp/go-link-968878995/000000.o: unknown file type

Try cleaning everything and trying again.

**Comment by xfengw** [comment] 2021-07-15 00:09
The same code, compiled successfully on my other computer, I don't know why this happens.

**Comment by lucor** [comment] 2021-08-20 09:23
It is difficult to debug with these info. Could you please provide a minimal example that reproduces the problem?
Additionally are you by any chance using a third party lib ? If so, please double check if that lib is compatible with android.

**Comment by andydotxyz** [comment] 2021-08-21 10:45
Are you certain that you cleaned all caches after compiling for a different architecture? It is worth checking

**Comment by andydotxyz** [comment] 2021-08-21 10:45
> It is difficult to debug with these info. Could you please provide a minimal example that reproduces the problem?
> Additionally are you by any chance using a third party lib ? If so, please double check if that lib is compatible with android.

I think he pasted the code above

**Comment by lucor** [comment] 2021-09-17 07:23
It was my understanding that the code provided [above](https://github.com/fyne-io/fyne-cross/issues/53#issuecomment-879727116) was working correctly, hence my question.
@xfengw could you please confirm and in case share the code along with the steps to reproduce the issue ?

**Comment by andydotxyz** [comment] 2021-09-21 16:27
Oh. My reading of it was that the pasted code worked on Windows but not Android. Hopefully @xfengw can clarify

**Comment by Beanzilla** [comment] 2022-09-26 22:05
Just updated fyne/mobile to 0.1.2 now I get this error:

```
[i] Target: android/multiple
[i] Cleaning target directories...
[✓] "dist" dir cleaned: /home/apollo/dev/go/fyne/Timey/fyne-cross/dist/android
[✓] "temp" dir cleaned: /home/apollo/dev/go/fyne/Timey/fyne-cross/tmp/android
[✓] "bin" dir cleaned: /home/apollo/dev/go/fyne/Timey/fyne-cross/bin/android
[i] Checking for go.mod: /home/apollo/dev/go/fyne/Timey/go.mod
[✓] go.mod found
[i] Packaging app...
2022/09/26 21:59:52 Unable to remove temporary build file /app/timey
go build -buildmode=c-shared -o /tmp/fyne-work-2401083611/lib/armeabi-v7a/libTimey.so red-green.com/timey failed: exit status 2
# github.com/fyne-io/mobile/app
ld: error: duplicate symbol: display
>>> defined at android.go:38
>>>            $WORK/b183/_x001.o:(display)
>>> defined at android.go:38 (/go/pkg/mod/github.com/fyne-io/mobile@v0.1.2/app/android.go:38)
>>>            $WORK/b183/_x002.o:(.bss+0x0)

ld: error: duplicate symbol: surface
>>> defined at android.go:39
>>>            $WORK/b183/_x001.o:(surface)
>>> defined at android.go:39 (/go/pkg/mod/github.com/fyne-io/mobile@v0.1.2/app/android.go:39)
>>>            $WORK/b183/_x002.o:(.bss+0x4)

ld: error: duplicate symbol: display
>>> defined at android.go:38
>>>            $WORK/b183/_x001.o:(display)
>>> defined at android.c:146
>>>            $WORK/b183/_x004.o:(.bss+0x18)

ld: error: duplicate symbol: surface
>>> defined at android.go:39
>>>            $WORK/b183/_x001.o:(surface)
>>> defined at android.c:147
>>>            $WORK/b183/_x004.o:(.bss+0x1C)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
# fyne.io/fyne/v2/internal/driver/mobile
android.c:51:9: warning: returning 'const char *' from a function with result type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
android.c:68:48: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
android.c:72:55: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
android.c:123:48: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
android.c:126:48: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
android.c:182:50: warning: passing 'char *' to parameter of type 'jbyte *' (aka 'signed char *') converts between pointers to integer types with different sign [-Wpointer-sign]
android.c:192:48: warning: passing 'char *' to parameter of type 'const jbyte *' (aka 'const signed char *') converts between pointers to integer types with different sign [-Wpointer-sign]
# fyne.io/fyne/v2/app
app_mobile_and.c:45:48: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
app_mobile_and.c:48:48: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
app_mobile_and.c:84:30: warning: incompatible integer to pointer conversion passing 'uintptr_t' (aka 'unsigned int') to parameter of type 'jobject' (aka 'void *') [-Wint-conversion]
app_mobile_and.c:97:33: warning: incompatible pointer to integer conversion passing 'JNIEnv *' (aka 'const struct JNINativeInterface **') to parameter of type 'uintptr_t' (aka 'unsigned int') [-Wint-conversion]
app_mobile_and.c:41:36: note: passing argument to parameter 'jni_env' here

[✗] could not package the Fyne app: could not package the Fyne app: exit status 1
```

Things I've done:

- [x] Blown away `~/.cache/fyne-cross/`
- [x] Blown away `fyne-cross` in the build/project directory
- [x] Built the project with fyne-cross for under native Linux amd64
- [x] Read this issue and some other issues in attempt to find a solution. (None found, as of yet, I hope)

**Comment by andydotxyz** [comment] 2022-09-27 16:17
You should not need to include `fyne/mobile` in a Fyne app, it will be included for you.
The error is due to you having multiple libraries add the same code, so either you have `fyne.io/fyne` plus the `mobile` project, or you are mixing `fyne.io/fyne` and `fyne.io/fyne/v2`.

**Comment by andydotxyz** [comment] 2022-09-27 16:19
I think that the original error was resolved above, and indeed the new question answered as well.
Closing before we get more questions on the same ticket ;).

**Closed by andydotxyz** 2022-09-27 16:19 UTC
Labels: question

**Comment by Beanzilla** [comment] 2022-09-27 18:00
Ok, Thank you for the help.

> That would explain why the example works just fine, because I don't mix `fyne` and `fyne/v2`.
