### ISSUE TITLE
Problem creating darwin image on M1 macos

### ISSUE THREAD

**Issue by realnbuz** [fyne-io/fyne-cross#50] opened 2021-06-03 22:39 UTC
Running fyne-cross dawrin-image on my new M1 Air. After an hour or so building various things, we eventually end with the following failure. Is there any additional info I can share to help diagnose?

macos 11.3.1, Command_Line_Tools_for_Xcode_12.5.dmg, docker 20.10.6, go 1.16.5 darwin/arm64

#12 2660.8 create_symlink x86_64-apple-darwin20.4-wrapper arm64e-apple-darwin20.4-xcodebuild
#12 2660.8 
#12 2661.1 
#12 2661.1 testing x86_64-apple-darwin20.4-clang++ -stdlib=libc++ -std=c++11 ... failed (ignored)
#12 2665.1 
#12 2665.1 testing x86_64h-apple-darwin20.4-clang ... works
#12 2665.9 testing x86_64h-apple-darwin20.4-clang++ ... Undefined symbols for architecture x86_64h:
#12 2670.3   "std::__1::locale::use_facet(std::__1::locale::id&) const", referenced from:
#12 2670.3       _main in test-8ae03b.o
#12 2670.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-8ae03b.o
#12 2670.3   "std::__1::ios_base::getloc() const", referenced from:
#12 2670.3       _main in test-8ae03b.o
#12 2670.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-8ae03b.o
#12 2670.3   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::put(char)", referenced from:
#12 2670.3       _main in test-8ae03b.o
#12 2670.3   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::flush()", referenced from:
#12 2670.3       _main in test-8ae03b.o
#12 2670.3   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)", referenced from:
#12 2670.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-8ae03b.o
#12 2670.3   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry()", referenced from:
#12 2670.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-8ae03b.o
#12 2670.3   "std::__1::cout", referenced from:
#12 2670.3       _main in test-8ae03b.o
#12 2670.3   "std::__1::ctype<char>::id", referenced from:
#12 2670.3       _main in test-8ae03b.o
#12 2670.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-8ae03b.o
#12 2670.3   "std::__1::locale::~locale()", referenced from:
#12 2670.3       _main in test-8ae03b.o
#12 2670.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-8ae03b.o
#12 2670.3   "std::__1::ios_base::__set_badbit_and_consider_rethrow()", referenced from:
#12 2670.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-8ae03b.o
#12 2670.3   "std::__1::ios_base::clear(unsigned int)", referenced from:
#12 2670.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-8ae03b.o
#12 2670.3   "std::terminate()", referenced from:
#12 2670.3       ___clang_call_terminate in test-8ae03b.o
#12 2670.3   "operator delete(void*)", referenced from:
#12 2670.3       std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in test-8ae03b.o
#12 2670.3   "operator new(unsigned long)", referenced from:
#12 2670.3       std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in test-8ae03b.o
#12 2670.3   "___cxa_begin_catch", referenced from:
#12 2670.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-8ae03b.o
#12 2670.3       ___clang_call_terminate in test-8ae03b.o
#12 2670.3   "___cxa_end_catch", referenced from:
#12 2670.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-8ae03b.o
#12 2670.3   "___gxx_personality_v0", referenced from:
#12 2670.3       _main in test-8ae03b.o
#12 2670.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-8ae03b.o
#12 2670.3       std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in test-8ae03b.o
#12 2670.3       Dwarf Exception Unwind Info (__eh_frame) in test-8ae03b.o
#12 2670.3 ld: symbol(s) not found for architecture x86_64h
#12 2670.3 clang: error: linker command failed with exit code 1 (use -v to see invocation)
#12 2670.3 failed (ignored)
#12 2670.3 
#12 2670.3 testing arm64-apple-darwin20.4-clang ... works
#12 2671.1 testing arm64-apple-darwin20.4-clang++ ... Undefined symbols for architecture arm64:
#12 2674.7   "std::__1::locale::use_facet(std::__1::locale::id&) const", referenced from:
#12 2674.7       _main in test-b43544.o
#12 2674.8       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-b43544.o
#12 2674.8   "std::__1::ios_base::getloc() const", referenced from:
#12 2674.8       _main in test-b43544.o
#12 2674.8       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-b43544.o
#12 2674.8   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::put(char)", referenced from:
#12 2674.8       _main in test-b43544.o
#12 2674.8   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::flush()", referenced from:
#12 2674.8       _main in test-b43544.o
#12 2674.8   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)", referenced from:
#12 2674.8       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-b43544.o
#12 2674.8   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry()", referenced from:
#12 2674.8       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-b43544.o
#12 2674.8   "std::__1::cout", referenced from:
#12 2674.8       _main in test-b43544.o
#12 2674.8   "std::__1::ctype<char>::id", referenced from:
#12 2674.8       _main in test-b43544.o
#12 2674.8       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-b43544.o
#12 2674.8   "std::__1::locale::~locale()", referenced from:
#12 2674.8       _main in test-b43544.o
#12 2674.8       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-b43544.o
#12 2674.8   "std::__1::ios_base::__set_badbit_and_consider_rethrow()", referenced from:
#12 2674.8       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-b43544.o
#12 2674.8   "std::__1::ios_base::clear(unsigned int)", referenced from:
#12 2674.8       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-b43544.o
#12 2674.8   "std::terminate()", referenced from:
#12 2674.8       ___clang_call_terminate in test-b43544.o
#12 2674.8   "operator delete(void*)", referenced from:
#12 2674.8       std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in test-b43544.o
#12 2674.8   "operator new(unsigned long)", referenced from:
#12 2674.8       std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in test-b43544.o
#12 2674.8   "___cxa_begin_catch", referenced from:
#12 2674.8       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-b43544.o
#12 2674.8       ___clang_call_terminate in test-b43544.o
#12 2674.8   "___cxa_end_catch", referenced from:
#12 2674.8       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-b43544.o
#12 2674.8   "___gxx_personality_v0", referenced from:
#12 2674.8       _main in test-b43544.o
#12 2674.8       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-b43544.o
#12 2674.8       std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in test-b43544.o
#12 2674.8 ld: symbol(s) not found for architecture arm64
#12 2674.8 clang: error: linker command failed with exit code 1 (use -v to see invocation)
#12 2674.8 failed (ignored)
#12 2674.8 
#12 2674.8 testing arm64e-apple-darwin20.4-clang ... ld: warning: object file /tmp/test-01b6fe.o was built with an incompatible arm64e ABI compiler
#12 2675.6 works
#12 2675.6 testing arm64e-apple-darwin20.4-clang++ ... ld: warning: object file /tmp/test-af06eb.o was built with an incompatible arm64e ABI compiler
#12 2679.7 Undefined symbols for architecture arm64e:
#12 2679.7   "std::__1::locale::use_facet(std::__1::locale::id&) const", referenced from:
#12 2679.7       _main in test-af06eb.o
#12 2679.7       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-af06eb.o
#12 2679.7   "std::__1::ios_base::getloc() const", referenced from:
#12 2679.7       _main in test-af06eb.o
#12 2679.7       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-af06eb.o
#12 2679.7   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::put(char)", referenced from:
#12 2679.7       _main in test-af06eb.o
#12 2679.7   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::flush()", referenced from:
#12 2679.7       _main in test-af06eb.o
#12 2679.7   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)", referenced from:
#12 2679.7       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-af06eb.o
#12 2679.7   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry()", referenced from:
#12 2679.7       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-af06eb.o
#12 2679.7   "std::__1::cout", referenced from:
#12 2679.7       _main in test-af06eb.o
#12 2679.7   "std::__1::ctype<char>::id", referenced from:
#12 2679.7       _main in test-af06eb.o
#12 2679.7       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-af06eb.o
#12 2679.7   "std::__1::locale::~locale()", referenced from:
#12 2679.7       _main in test-af06eb.o
#12 2679.7       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-af06eb.o
#12 2679.7   "std::__1::ios_base::__set_badbit_and_consider_rethrow()", referenced from:
#12 2679.7       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-af06eb.o
#12 2679.7   "std::__1::ios_base::clear(unsigned int)", referenced from:
#12 2679.7       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-af06eb.o
#12 2679.7   "std::terminate()", referenced from:
#12 2679.7       ___clang_call_terminate in test-af06eb.o
#12 2679.7   "operator delete(void*)", referenced from:
#12 2679.7       std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in test-af06eb.o
#12 2679.7   "operator new(unsigned long)", referenced from:
#12 2679.7       std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in test-af06eb.o
#12 2679.7   "___cxa_begin_catch", referenced from:
#12 2679.7       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-af06eb.o
#12 2679.7       ___clang_call_terminate in test-af06eb.o
#12 2679.7   "___cxa_end_catch", referenced from:
#12 2679.7       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-af06eb.o
#12 2679.7   "___gxx_personality_v0", referenced from:
#12 2679.7       _main in test-af06eb.o
#12 2679.7       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-af06eb.o
#12 2679.7       std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in test-af06eb.o
#12 2679.7 ld: symbol(s) not found for architecture arm64e
#12 2679.7 clang: error: linker command failed with exit code 1 (use -v to see invocation)
#12 2679.7 failed (ignored)
#12 2679.7 
#12 2679.7 testing x86_64-apple-darwin20.4-clang ... works
#12 2680.5 testing x86_64-apple-darwin20.4-clang++ ... Undefined symbols for architecture x86_64:
#12 2684.3   "std::__1::locale::use_facet(std::__1::locale::id&) const", referenced from:
#12 2684.3       _main in test-9eee1a.o
#12 2684.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-9eee1a.o
#12 2684.3   "std::__1::ios_base::getloc() const", referenced from:
#12 2684.3       _main in test-9eee1a.o
#12 2684.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-9eee1a.o
#12 2684.3   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::put(char)", referenced from:
#12 2684.3       _main in test-9eee1a.o
#12 2684.3   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::flush()", referenced from:
#12 2684.3       _main in test-9eee1a.o
#12 2684.3   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)", referenced from:
#12 2684.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-9eee1a.o
#12 2684.3   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry()", referenced from:
#12 2684.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-9eee1a.o
#12 2684.3   "std::__1::cout", referenced from:
#12 2684.3       _main in test-9eee1a.o
#12 2684.3   "std::__1::ctype<char>::id", referenced from:
#12 2684.3       _main in test-9eee1a.o
#12 2684.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-9eee1a.o
#12 2684.3   "std::__1::locale::~locale()", referenced from:
#12 2684.3       _main in test-9eee1a.o
#12 2684.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-9eee1a.o
#12 2684.3   "std::__1::ios_base::__set_badbit_and_consider_rethrow()", referenced from:
#12 2684.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-9eee1a.o
#12 2684.3   "std::__1::ios_base::clear(unsigned int)", referenced from:
#12 2684.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-9eee1a.o
#12 2684.3   "std::terminate()", referenced from:
#12 2684.3       ___clang_call_terminate in test-9eee1a.o
#12 2684.3   "operator delete(void*)", referenced from:
#12 2684.3       std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in test-9eee1a.o
#12 2684.3   "operator new(unsigned long)", referenced from:
#12 2684.3       std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in test-9eee1a.o
#12 2684.3   "___cxa_begin_catch", referenced from:
#12 2684.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-9eee1a.o
#12 2684.3       ___clang_call_terminate in test-9eee1a.o
#12 2684.3   "___cxa_end_catch", referenced from:
#12 2684.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-9eee1a.o
#12 2684.3   "___gxx_personality_v0", referenced from:
#12 2684.3       _main in test-9eee1a.o
#12 2684.3       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in test-9eee1a.o
#12 2684.3       std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in test-9eee1a.o
#12 2684.3       Dwarf Exception Unwind Info (__eh_frame) in test-9eee1a.o
#12 2684.3 ld: symbol(s) not found for architecture x86_64
#12 2684.3 clang: error: linker command failed with exit code 1 (use -v to see invocation)
#12 2684.3 
#12 2684.3 exiting with abnormal exit code (1)
#12 2684.3 run 'OCDEBUG=1 ./build.sh' to enable debug messages
#12 2684.3 
------
executor failed running [/bin/sh -c UNATTENDED=yes SDK_VERSION=${SDK_VERSION} OSX_VERSION_MIN=${OSX_VERSION_MIN} ./build.sh]: exit code: 1
[✗] could not create the docker darwin image: exit status 1

**Comment by andydotxyz** [comment] 2021-06-04 07:32
This is a known issue, duplicate of #48

**Closed by andydotxyz** 2021-06-04 07:32 UTC
