### ISSUE TITLE
Android apk - "There was a problem parsing the package."

### ISSUE THREAD

**Issue by test1543** [fyne-io/fyne-cross#25] opened 2021-01-10 19:42 UTC
I installed fyne-cross on Xubuntu 20.04. No Android Studio, SDK, NDK, just plain fresh Xubuntun 20.04 plus the fyne cross installation guide. When building the example for Windows (fyne-cross windows), this works like a charm and the resulting exe runs smoothly on Windows 10. Building for Android (fyne-cross android) works as well without any error message (though the resulting apk comes in at about 54M). When transferring the apk to an Android device and trying to install it (Android 6 and Android 8) I get an error message "There was a problem parsing the package.".

Any idea what I am missing?

**Comment by test1543** [comment] 2021-01-11 00:38
Ok, I figured this out myself. When cross-compiling for Android, the -app-id is not optional. Also, to generate a release version, lot of additional info is neede. So a simple test must be of the format
$ fyne-cross android -debug -app-id <app-id>

Delete if you please. I write this down as reference for other noobs. It took me some hours that I might spare someone else.

**Comment by andydotxyz** [comment] 2021-01-11 10:53
Thanks for reporting this. Really we should not default the -app-id parameter as it is critical that the developer sets it correctly.
I am re-opening this ticket until the issue is correctly resolved.

**Comment by lucor** [comment] 2021-02-06 15:21
Fixed via #26 and availabled in develop

**Closed by lucor** 2021-02-06 15:21 UTC
Labels: bug
