### ISSUE TITLE
missing appID parameter for package

### ISSUE THREAD

**Issue by chrions** [fyne-io/fyne-cross#197] opened 2023-05-14 14:24 UTC
When I pack windows program on mac,  I use  **fyne-cross windows -arch=amd64 386**

```
fyne-cross windows -arch=amd64 386
[i] Target: windows/amd64
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /app/fyne-cross/bin/windows-amd64
[✓] "dist" dir cleaned: /app/fyne-cross/dist/windows-amd64
[✓] "temp" dir cleaned: /app/fyne-cross/tmp/windows-amd64
[i] Checking for go.mod: /Users/fyf/go/src/web3_project/scroll/go.mod
[✓] go.mod found
[i] Packaging app...
missing appID parameter for package
[✗] could not package the Fyne app: exit status 1

```
Why did you report an error, what is appID and how should I solve it?

**Comment by andydotxyz** [comment] 2023-05-14 18:52
It is the unique id of the application, required by some OS. I think we have some documentation at https://developer.fyne.io/started/distribution.html.

This feels like a duplicate of #46.

**Comment by Jacalz** [comment] 2023-12-04 10:32
Will close this as a duplicate of #46. The support for `FyneApp.toml` has improved things considerably but I agree that we should update the documentation.

**Closed by Jacalz** 2023-12-04 10:32 UTC
