### ISSUE TITLE
fyne-cross does not respect vendoring

### ISSUE THREAD

**Issue by Uldiniad** [fyne-io/fyne-cross#5] opened 2020-11-12 16:04 UTC
Hi,

we're using fyne for our cross-platform Android factory image flasher (https://github.com/AOSPAlliance/device-flasher)

I noticed that fyne-cross builds the application even when there are missing dependencies in vendor (go build fails).

Wanted to ask if this is expected and what should be done.

Thank you

**Comment by lucor** [comment] 2020-11-12 19:13
fyne-cross uses by default go modules, and the expected behaviour should be the same as reported here: https://golang.org/ref/mod#vendoring

@Uldiniad could you please report some info that could help to debug like the command executed, the error you're getting, OS ecc ?

I did a quick test building locally your project and I'm getting the following error against android:
`gitlab.com/calyxos/device-flasher does not import "github.com/fyne-io/mobile/app"`

Extract of the debug output is:
```
fyne-cross android -debug
...
fyne cli version v1.4.0
/usr/bin/docker run --rm -t -w /app/. -v /code/lucor/device-flasher:/app -v /home/lucor/.cache/fyne-cross:/go -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e fyne_uid=1000 fyneio/fyne-cross:android-latest /usr/local/bin/fyne package -os android -name device-flasher -icon /app/fyne-cross/tmp/android/Icon.png -appID device-flasher
gitlab.com/calyxos/device-flasher does not import "github.com/fyne-io/mobile/app"
```

As additional notes:
- the apk seems correcly produced under the project root
- building against linux do not report any error

/cc @andydotxyz 

@Uldiniad please note that the docker base image ships with go 1.13

**Comment by Uldiniad** [comment] 2020-11-12 23:05
the tools is meant to run on desktop operating systems, I'm compiling on windows but we the tools is released for darwin, linux and windows targets. thanks for the note on the go version in the docker image.
From golang documentation, "If the vendor directory is present in the main module's root directory, it will be used automatically if the go version in the main module's go.mod file is 1.14 or higher. To explicitly enable vendoring, invoke the go command with the flag -mod=vendor. To disable vendoring, use the flag -mod=mod."
Is it possible to pass -mod=vendor to fyne-cross somehow?

**Comment by lucor** [comment] 2020-11-13 11:39
it is not possible to specify the `-mod` at the moment. 
Anyway the issue seems not related to the `vendor` folder stuff (i.e. removing it go should automatically download all the dependencies) but to the build tag `GUI` specified into the `gui.go` and `cli.go` files.

Removing it from the `gui.go` file and updating the one into the `cli.go` file like `// +build cli` should allow the compilation and you'd find a `device_flasher.apk` file under your project root.

Please note that you'll get an error like:
```
[✗] rename /path/to/device-flasher/device-flasher.apk /path/to/device-flasher/fyne-cross/dist/android/device-flasher.apk: no such file or directory
```
but this is a different bug: the tool is expecting `device-flasher.apk` but fyne cli generate it as `device_flasher.apk`

**Comment by chirayudesai** [comment] 2020-11-13 15:56
Hi, I am one of the developers working on `device-flasher`

> it is not possible to specify the `-mod` at the moment.

:( Any ideas if it'll be supported in the future?
> Anyway the issue seems not related to the `vendor` folder stuff (i.e. removing it go should automatically download all the dependencies) but to the build tag `GUI` specified into the `gui.go` and `cli.go` files.

This is exactly what we want to avoid, we specifically vendored the dependencies.
I had a hack in mind involving the `-cache` option - pointing that to a directory in our source, and then replicating the vendor structure there to make it use those. It'd still download anything missing, but at least it'd use what we already have.
> 
> Removing it from the `gui.go` file and updating the one into the `cli.go` file like `// +build cli` should allow the compilation and you'd find a `device_flasher.apk` file under your project root.
> 
> Please note that you'll get an error like:
> 
> ```
> [✗] rename /path/to/device-flasher/device-flasher.apk /path/to/device-flasher/fyne-cross/dist/android/device-flasher.apk: no such file or directory
> ```
> 
> but this is a different bug: the tool is expecting `device-flasher.apk` but fyne cli generate it as `device_flasher.apk`

GUI tag works fine for windows/darwin/linux with both `go build` and `fyne-cross`
It's meant to install an OS on Android devices, but it won't work on Android itself, so we aren't building it for android - which is why the apk build was having issue earlier / why we aren't importing `mobile/app` from the earlier comment.

**Comment by chirayudesai** [comment] 2020-11-13 16:02
Basically, the way testing this is:

* `make` - works (This calls go build with the correct options)
* `fyne-cross windows -tags "GUI"` - works (and for darwin / linux too)

Now, for testing, `rm -rf vendor/golang.org` - just a directory we picked inside `vendor`
* `make` - fails (since it can't find packages)
* `fyne-cross windows -tags "GUI"` - still works, since it downloads any missing dependencies like you mentioned earlier.

That last part is what we want to avoid, if possible.

**Comment by lucor** [comment] 2020-11-13 19:24
@chirayudesai thanks for the additional details, they helped to understand your use case.
wrt the android issue it is related to how fyne-cross works under the hood.
To compile and generate the apk, it uses the [fyne cli tool](https://developer.fyne.io/started/distribution#mobile).
This tool at the moment does not allow to specify any build tag so basically the gui.go file with the "GUI" build constraint is ignored but some of the fyne deps are still compiled due to the GOOS=android constraint hence the warning/error.

As temporary workaround, until the fyne tool is updated, you'd change the build constraints with something like below:
- `cli.go` -> `// +build !GUI,!android`
- `gui.go` -> `// +build GUI android`

**Comment by chirayudesai** [comment] 2020-11-14 00:07
> @chirayudesai thanks for the additional details, they helped to understand your use case.

Glad to hear that. Hope we can figure something out about vendoring.

> wrt the android issue it is related to how fyne-cross works under the hood.
> To compile and generate the apk, it uses the [fyne cli tool](https://developer.fyne.io/started/distribution#mobile).
> This tool at the moment does not allow to specify any build tag so basically the gui.go file with the "GUI" build constraint is ignored but some of the fyne deps are still compiled due to the GOOS=android constraint hence the warning/error.
> 
> As temporary workaround, until the fyne tool is updated, you'd change the build constraints with something like below:
> 
> * `cli.go` -> `// +build !GUI,!android`
> * `gui.go` -> `// +build GUI android`

Gotcha. We don't compile for android though, so this is not an issue for us at the moment, but it's useful info for anybody else who hits this, and also if we do another project in the future.

Thanks for your super prompt responses!

**Comment by andydotxyz** [comment] 2020-11-14 11:36
I'm a little confused about this - if the project does not want to use modules when building then why have a `go.mod` file?
Is this because there are local modifications committed to the vendor folder perhaps?

**Comment by chirayudesai** [comment] 2020-11-23 21:56
> I'm a little confused about this - if the project does not want to use modules when building then why have a `go.mod` file?
> Is this because there are local modifications committed to the vendor folder perhaps?

We want to use modules, but we don't want to download them during build-time. We'd like to have our 'vendor' directory created using `go mod vendor` be used instead. There are no local modifications there (and won't be), we just run `go mod vendor` to populate it and then commit that.


I think that trying go 1.14 or higher inside the container might work, given how that's supposed to use vendor automatically. See https://golang.org/ref/mod#vendoring

**Comment by lucor** [comment] 2020-12-06 11:17
The version landed in devolop supports tags and allows to specify env vars with `=` chars. 
The following should work now:
```
fyne-cross linux -tags GUI -env "GOFLAGS=-mod=vendor"
```

**Comment by andydotxyz** [comment] 2020-12-06 11:57
Tested the PR https://github.com/fyne-io/fyne-cross/pull/14 and it does resolve this issue

**Comment by lucor** [comment] 2020-12-26 18:41
Features released in 1.0.0, going to close the issue. Feel free to re-open if you find any issue.

**Closed by lucor** 2020-12-26 18:41 UTC

**Comment by chirayudesai** [comment] 2021-01-16 18:29
> Features released in 1.0.0, going to close the issue. Feel free to re-open if you find any issue.

Thank you, it works well!

**Comment by prologic** [comment] 2022-05-21 03:29
I'm a bit confused by this too.

I'm running:

```#!sh
$ fyne package -os ios -appID com.example.fybro -icon Icon.png
github.com/andydotxyz/fybro does not import "github.com/fyne-io/mobile/app"
```

How is one suppose to use and import `github.com/fyne-io/mobile/app`?

**Comment by prologic** [comment] 2022-05-21 03:34
Actually nevermind. Lock this issue.

Problem: Had an old version of `fyne` (the cli) installed

```#!sh
$ fyne version
fyne cli version v1.4.2
```

Updated to v2.1.4 with:

```#!sh
$ go install fyne.io/fyne/v2/cmd/fyne@latest
$ fyne version
fyne cli version: v2.1.4
```

And packaging now works! 🥳
