### ISSUE TITLE
could not clean the "bin" dir

### ISSUE THREAD

**Issue by philiplb** [fyne-io/fyne-cross#217] opened 2023-12-25 20:58 UTC
### Describe the bug:

I have the hello-world Fyne program and want to cross compile it from MacOS, M1 CPU. It fails with this error message: "could not clean the "bin" dir".

### To Reproduce:
Steps to reproduce the behaviour:
1. Run `fyne-cross darwin -arch=amd64 -debug -no-cache -app-id=de.philiplb.foo` in the source folder.

### Device and debug info (please complete the following information):

<summary>Device info</summary>

 - **OS:** MacOS
 - **Version:** 14.0
 - **Go version:** 1.21.5
 - **fyne-cross version:** 1.4.0
 - **Fyne version:** 2.4.3

<details><summary>Debug info</summary><br><pre>

```bash
fyne-cross darwin -arch=amd64 -debug -no-cache -app-id=de.philiplb.foo
```

> [i] Target: darwin/amd64
> &command.localContainerImage{baseContainerImage:command.baseContainerImage{arch:"amd64", os:"darwin", id:"darwin-amd64", env:map[string]string{"CC":"zig cc -v -target x86_64-macos.10.12 -isysroot /sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks", "CGO_LDFLAGS":"--sysroot /sdk -F/System/Library/Frameworks -L/usr/lib", "CXX":"zig c++ -v -target x86_64-macos.10.12 -isysroot /sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks", "GOARCH":"amd64", "GOOS":"darwin"}, tags:[]string(nil), mount:[]command.containerMountPoint{command.containerMountPoint{name:"project", localHost:"/Users/philiplb/repos/foo/src", inContainer:"/app"}}, DockerImage:"docker.io/fyneio/fyne-cross-images:darwin"}, runner:(*command.localContainerEngine)(0x1400014e090)}
> [i] Cleaning target directories...
> /usr/local/bin/docker run --rm -t -w /app -v /Users/philiplb/repos/foo/src:/app --platform linux/arm64 -u 501:20 --entrypoint fixuid -v /private/tmp/com.apple.launchd.VlhzF6pzTy/Listeners:/tmp/ssh-agent -e SSH_AUTH_SOCK=/tmp/ssh-agent -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e "GOFLAGS=-ldflags=-s -ldflags=-w" -e CGO_LDFLAGS=--sysroot /sdk -F/System/Library/Frameworks -L/usr/lib -e GOOS=darwin -e GOARCH=amd64 -e CC=zig cc -v -target x86_64-macos.10.12 -isysroot /sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks -e CXX=zig c++ -v -target x86_64-macos.10.12 -isysroot /sdk -iwithsysroot /usr/include -iframeworkwithsysroot /System/Library/Frameworks docker.io/fyneio/fyne-cross-images:darwin rm -rf /app/fyne-cross/bin/darwin-amd64
> docker: Error response from daemon: error while creating mount source path '/host_mnt/private/tmp/com.apple.launchd.VlhzF6pzTy/Listeners': mkdir /host_mnt/private/tmp/com.apple.launchd.VlhzF6pzTy/Listeners: operation not supported.
> [✗] could not clean the "bin" dir /app/fyne-cross/bin/darwin-amd64: exit status 125

**Comment by andydotxyz** [comment] 2023-12-25 21:17
Dupe of #214, it's fixed already but not released yet iirc.

**Closed** 2023-12-25 21:18 UTC
Labels: duplicate

**Comment by philiplb** [comment] 2023-12-25 21:31
I see, thank you very much!
And merry christmas :)
